parallel-jobs = 1
# patches-version = "dev"
# cli-version = "dev"
enable-module-update = true

[battery-guru-morphe]
enabled = true
app-name = "battery-guru"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://battery-guru.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/paget96/battery-guru-health-saver/"
dpi = "nodpi anydpi"
# archive-dlurl = "https://archive.org/download/geologically/apks/tv.twitch.android.app"

[money-manager-morphe]
enabled = true
app-name = "money-manager"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://money-manager.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/realbyte-inc/money-manager-expense-budget"
dpi = "nodpi anydpi"
# archive-dlurl = "https://archive.org/download/geologically/apks/tv.twitch.android.app"